# Blacklist

In [1]:
#importing libraries

import pandas as pd
import numpy as np

In [2]:
#import first csv file

fishdf=pd.read_csv("../data_wrangling/fishvessel_clean.csv")

In [3]:
#import second csv file

illegaldf=pd.read_csv("../data_wrangling/ts_clean.csv")

In [4]:
fishdf.head()

mmsi flag gear_type     length     tonnage  engine_power country  \
0  603100157  AGO  trawlers  32.808468  299.003814    733.826977  Angola   
1  603100137  AGO  trawlers  34.568782  395.683171    864.960188  Angola   
2  603100161  AGO  trawlers  28.822140  263.849149    651.809642  Angola   
3  603100174  AGO  trawlers  30.721429  299.700916    703.796086  Angola   
4  603100164  AGO  trawlers  37.479248  405.967747    850.976640  Angola   

   IUU Fishing  
0         2.37  
1         2.37  
2         2.37  
3         2.37  
4         2.37

In [5]:
illegaldf.head()

fishing_vessel_mmsi  transshipment_vessel_mmsi                 start_time  \
0            416565000                  354240000  2016-11-18 14:30:00+00:00   
1            412679190                  354240000  2016-12-11 14:50:00+00:00   
2            440863000                  354240000  2017-06-13 12:50:00+00:00   
3            416563000                  354240000  2016-11-15 11:30:00+00:00   
4            441309000                  354240000  2017-05-19 00:40:00+00:00   

                    end_time  mean_latitude  mean_longitude  duration_hr  \
0  2016-11-19 01:50:00+00:00     -17.039085      -79.063725    11.333333   
1  2016-12-11 19:50:00+00:00     -20.269608      -79.244953     5.000000   
2  2017-06-15 01:20:00+00:00     -62.640767      -60.690240    36.500000   
3  2016-11-16 04:00:00+00:00     -17.046586      -79.061923    16.500000   
4  2017-05-19 20:50:00+00:00     -46.627878      -60.554922    20.166667   

   median_distance_km  median_speed_knots  \
0            0.038188            0.585402   
1            0.020033            0.575663   
2            0.054992            0.019775   
3            0.036427            1.023917   
4            0.034053            0.544031   

                                 coordinates     country iso_3  
0           (-17.0390854214, -79.0637246039)  Antarctica   ATA  
1   (-20.26960835264285, -79.24495254404286)  Antarctica   ATA  
2  (-62.64076718797922, -60.690240192925565)         NaN   NaN  
3   (-17.046585915013658, -79.0619234553677)  Antarctica   ATA  
4   (-46.62787804705882, -60.55492183696471)         NaN   NaN

In [7]:
illegaldf.index

RangeIndex(start=0, stop=11681, step=1)

In [ ]:
# I can try a relation mmsi (country), transhipment vessel id and IUU

In [8]:
#merging the illegal encounters to analyse

fishillegaldf=fishdf.merge(illegaldf, left_on='mmsi', right_on='fishing_vessel_mmsi')

In [9]:
fishillegaldf.head()

mmsi flag      gear_type     length    tonnage  engine_power  \
0  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
1  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
2  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
3  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
4  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   

   country_x  IUU Fishing  fishing_vessel_mmsi  transshipment_vessel_mmsi  \
0  Australia         1.91            503584700                  352241000   
1  Australia         1.91            503584700                  576419000   
2  Australia         1.91            503584700                  576107000   
3  Australia         1.91            503584700                  576107000   
4  Australia         1.91            503584700                  576107000   

                  start_time                   end_time  mean_latitude  \
0  2015-07-04 23:50:00+00:00  2015-07-05 02:00:00+00:00     -34.691229   
1  2013-08-10 03:20:00+00:00  2013-08-10 05:20:00+00:00     -34.690805   
2  2014-07-12 01:10:00+00:00  2014-07-12 03:10:00+00:00     -34.692003   
3  2014-07-19 04:40:00+00:00  2014-07-19 08:30:00+00:00     -34.695524   
4  2014-07-13 23:50:00+00:00  2014-07-15 02:10:00+00:00     -34.695280   

   mean_longitude  duration_hr  median_distance_km  median_speed_knots  \
0      136.085965     2.166667            0.069157            0.031628   
1      136.085175     2.000000            0.027717            0.024307   
2      136.099495     2.000000            0.041409            0.018666   
3      136.094849     3.833333            0.044934            0.029034   
4      136.099197    26.333333            0.039192            0.016855   

                                 coordinates country_y iso_3  
0       (-34.6912286908, 136.08596549450002)       NaN   NaN  
1           (-34.6908052868, 136.0851747694)       NaN   NaN  
2          (-34.69200326485, 136.0994946767)       NaN   NaN  
3  (-34.695523965300005, 136.09484891575002)       NaN   NaN  
4  (-34.695280009899996, 136.09919684837502)       NaN   NaN

In [11]:
fishillegaldf['id_encounter'] = fishillegaldf.index

In [12]:
fishillegaldf.head()

mmsi flag      gear_type     length    tonnage  engine_power  \
0  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
1  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
2  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
3  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
4  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   

   country_x  IUU Fishing  fishing_vessel_mmsi  transshipment_vessel_mmsi  \
0  Australia         1.91            503584700                  352241000   
1  Australia         1.91            503584700                  576419000   
2  Australia         1.91            503584700                  576107000   
3  Australia         1.91            503584700                  576107000   
4  Australia         1.91            503584700                  576107000   

   ...                   end_time mean_latitude  mean_longitude  duration_hr  \
0  ...  2015-07-05 02:00:00+00:00    -34.691229      136.085965     2.166667   
1  ...  2013-08-10 05:20:00+00:00    -34.690805      136.085175     2.000000   
2  ...  2014-07-12 03:10:00+00:00    -34.692003      136.099495     2.000000   
3  ...  2014-07-19 08:30:00+00:00    -34.695524      136.094849     3.833333   
4  ...  2014-07-15 02:10:00+00:00    -34.695280      136.099197    26.333333   

   median_distance_km  median_speed_knots  \
0            0.069157            0.031628   
1            0.027717            0.024307   
2            0.041409            0.018666   
3            0.044934            0.029034   
4            0.039192            0.016855   

                                 coordinates country_y iso_3 id_encounter  
0       (-34.6912286908, 136.08596549450002)       NaN   NaN            0  
1           (-34.6908052868, 136.0851747694)       NaN   NaN            1  
2          (-34.69200326485, 136.0994946767)       NaN   NaN            2  
3  (-34.695523965300005, 136.09484891575002)       NaN   NaN            3  
4  (-34.695280009899996, 136.09919684837502)       NaN   NaN            4  

[5 rows x 21 columns]

In [13]:
#check columns

fishillegaldf.columns

Index(['mmsi', 'flag', 'gear_type', 'length', 'tonnage', 'engine_power',
       'country_x', 'IUU Fishing', 'fishing_vessel_mmsi',
       'transshipment_vessel_mmsi', 'start_time', 'end_time', 'mean_latitude',
       'mean_longitude', 'duration_hr', 'median_distance_km',
       'median_speed_knots', 'coordinates', 'country_y', 'iso_3',
       'id_encounter'],
      dtype='object')

In [14]:

fishillegaldf.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            10520, 10521, 10522, 10523, 10524, 10525, 10526, 10527, 10528,
            10529],
           dtype='int64', length=10530)

In [15]:
columns_drop=['mmsi', 'flag', 'gear_type', 'length', 'tonnage', 'engine_power','fishing_vessel_mmsi','transshipment_vessel_mmsi', 'start_time', 'end_time', 'mean_latitude','mean_longitude', 'duration_hr', 'median_distance_km','median_speed_knots', 'coordinates', 'country_y', 'iso_3']

In [16]:
fishillegaldf=fishillegaldf.drop(columns_drop, axis=1)

In [17]:
fishillegaldf.head()

country_x  IUU Fishing  id_encounter
0  Australia         1.91             0
1  Australia         1.91             1
2  Australia         1.91             2
3  Australia         1.91             3
4  Australia         1.91             4

In [24]:
fishillegaldf=fishillegaldf.rename(columns={'country_x':'country'})

In [25]:
fishillegaldf.head()

country  IUU Fishing  id_encounter
0  Australia         1.91             0
1  Australia         1.91             1
2  Australia         1.91             2
3  Australia         1.91             3
4  Australia         1.91             4

In [26]:
nr_occurrences=(fishillegaldf.groupby('country').agg({'country':'count'})
                     .rename(columns={'country':"nr_occurrences"})
                     .reset_index())

In [27]:
nr_occurrences.head()

country  nr_occurrences
0  Australia               5
1     Belize               4
2   Cambodia              25
3     Canada             183
4      Chile              11

In [29]:
totaldf = fishillegaldf.merge(nr_occurrences, how="left", on="country")

In [30]:
totaldf

country  IUU Fishing  id_encounter  nr_occurrences
0      Australia         1.91             0               5
1      Australia         1.91             1               5
2      Australia         1.91             2               5
3      Australia         1.91             3               5
4      Australia         1.91             4               5
...          ...          ...           ...             ...
10525    Vanuatu         2.55         10525             133
10526    Vanuatu         2.55         10526             133
10527    Vanuatu         2.55         10527             133
10528    Vanuatu         2.55         10528             133
10529    Vanuatu         2.55         10529             133

[10530 rows x 4 columns]

In [31]:
features = totaldf.pivot_table(index="country",
                    columns="id_encounter",
                    values="IUU Fishing")

In [32]:
features

id_encounter                     0      1      2      3      4      5      \
country                                                                     
Australia                         1.91   1.91   1.91   1.91   1.91    NaN   
Belize                             NaN    NaN    NaN    NaN    NaN   1.78   
Cambodia                           NaN    NaN    NaN    NaN    NaN    NaN   
Canada                             NaN    NaN    NaN    NaN    NaN    NaN   
Chile                              NaN    NaN    NaN    NaN    NaN    NaN   
China                              NaN    NaN    NaN    NaN    NaN    NaN   
Colombia                           NaN    NaN    NaN    NaN    NaN    NaN   
Comoros                            NaN    NaN    NaN    NaN    NaN    NaN   
Côte d'Ivoire                      NaN    NaN    NaN    NaN    NaN    NaN   
Fiji                               NaN    NaN    NaN    NaN    NaN    NaN   
Germany                            NaN    NaN    NaN    NaN    NaN    NaN   
Iceland                            NaN    NaN    NaN    NaN    NaN    NaN   
India                              NaN    NaN    NaN    NaN    NaN    NaN   
Iran, Islamic Republic of          NaN    NaN    NaN    NaN    NaN    NaN   
Japan                              NaN    NaN    NaN    NaN    NaN    NaN   
Kiribati                           NaN    NaN    NaN    NaN    NaN    NaN   
Korea, Republic of                 NaN    NaN    NaN    NaN    NaN    NaN   
Latvia                             NaN    NaN    NaN    NaN    NaN    NaN   
Lithuania                          NaN    NaN    NaN    NaN    NaN    NaN   
Micronesia, Federated States of    NaN    NaN    NaN    NaN    NaN    NaN   
Netherlands                        NaN    NaN    NaN    NaN    NaN    NaN   
Norway                             NaN    NaN    NaN    NaN    NaN    NaN   
Oman                               NaN    NaN    NaN    NaN    NaN    NaN   
Papua New Guinea                   NaN    NaN    NaN    NaN    NaN    NaN   
Peru                               NaN    NaN    NaN    NaN    NaN    NaN   
Philippines                        NaN    NaN    NaN    NaN    NaN    NaN   
Poland                             NaN    NaN    NaN    NaN    NaN    NaN   
Russian Federation                 NaN    NaN    NaN    NaN    NaN    NaN   
Saint Kitts and Nevis              NaN    NaN    NaN    NaN    NaN    NaN   
Seychelles                         NaN    NaN    NaN    NaN    NaN    NaN   
Spain                              NaN    NaN    NaN    NaN    NaN    NaN   
Taiwan, Province of China          NaN    NaN    NaN    NaN    NaN    NaN   
Thailand                           NaN    NaN    NaN    NaN    NaN    NaN   
Ukraine                            NaN    NaN    NaN    NaN    NaN    NaN   
United Kingdom                     NaN    NaN    NaN    NaN    NaN    NaN   
United States                      NaN    NaN    NaN    NaN    NaN    NaN   
Vanuatu                            NaN    NaN    NaN    NaN    NaN    NaN   

id_encounter                     6      7      8      9      ...  10520  \
country                                                      ...          
Australia                          NaN    NaN    NaN    NaN  ...    NaN   
Belize                            1.78   1.78   1.78    NaN  ...    NaN   
Cambodia                           NaN    NaN    NaN    NaN  ...    NaN   
Canada                             NaN    NaN    NaN   1.97  ...    NaN   
Chile                              NaN    NaN    NaN    NaN  ...    NaN   
China                              NaN    NaN    NaN    NaN  ...    NaN   
Colombia                           NaN    NaN    NaN    NaN  ...    NaN   
Comoros                            NaN    NaN    NaN    NaN  ...    NaN   
Côte d'Ivoire                      NaN    NaN    NaN    NaN  ...    NaN   
Fiji                               NaN    NaN    NaN    NaN  ...    NaN   
Germany                            NaN    NaN    NaN    NaN  ...    NaN   
Iceland              

In [33]:
features=features.fillna(0)

In [34]:
features.head()

id_encounter  0      1      2      3      4      5      6      7      8      \
country                                                                       
Australia      1.91   1.91   1.91   1.91   1.91   0.00   0.00   0.00   0.00   
Belize         0.00   0.00   0.00   0.00   0.00   1.78   1.78   1.78   1.78   
Cambodia       0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
Canada         0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
Chile          0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   

id_encounter  9      ...  10520  10521  10522  10523  10524  10525  10526  \
country              ...                                                    
Australia      0.00  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
Belize         0.00  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
Cambodia       0.00  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
Canada         1.97  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
Chile          0.00  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

id_encounter  10527  10528  10529  
country                            
Australia       0.0    0.0    0.0  
Belize          0.0    0.0    0.0  
Cambodia        0.0    0.0    0.0  
Canada          0.0    0.0    0.0  
Chile           0.0    0.0    0.0  

[5 rows x 10530 columns]

In [35]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import NearestNeighbors

%matplotlib inline

In [36]:

from scipy.sparse import csr_matrix

In [37]:

country_features = csr_matrix(features)

In [ ]:
#train the model

In [38]:
model_knn = NearestNeighbors(metric="cosine",
                             algorithm="brute",
                             n_jobs=-1)
model_knn.fit(country_features)

NearestNeighbors(algorithm='brute', metric='cosine', n_jobs=-1)

In [41]:
features.head()

id_encounter  0      1      2      3      4      5      6      7      8      \
country                                                                       
Australia      1.91   1.91   1.91   1.91   1.91   0.00   0.00   0.00   0.00   
Belize         0.00   0.00   0.00   0.00   0.00   1.78   1.78   1.78   1.78   
Cambodia       0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
Canada         0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
Chile          0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   

id_encounter  9      ...  10520  10521  10522  10523  10524  10525  10526  \
country              ...                                                    
Australia      0.00  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
Belize         0.00  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
Cambodia       0.00  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
Canada         1.97  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
Chile          0.00  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

id_encounter  10527  10528  10529  
country                            
Australia       0.0    0.0    0.0  
Belize          0.0    0.0    0.0  
Cambodia        0.0    0.0    0.0  
Canada          0.0    0.0    0.0  
Chile           0.0    0.0    0.0  

[5 rows x 10530 columns]

In [49]:
features.loc['China'].values.reshape(1, -1)

array([[0., 0., 0., ..., 0., 0., 0.]])

In [50]:
features.index.tolist()

['Australia',
 'Belize',
 'Cambodia',
 'Canada',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 "Côte d'Ivoire",
 'Fiji',
 'Germany',
 'Iceland',
 'India',
 'Iran, Islamic Republic of',
 'Japan',
 'Kiribati',
 'Korea, Republic of',
 'Latvia',
 'Lithuania',
 'Micronesia, Federated States of',
 'Netherlands',
 'Norway',
 'Oman',
 'Papua New Guinea',
 'Peru',
 'Philippines',
 'Poland',
 'Russian Federation',
 'Saint Kitts and Nevis',
 'Seychelles',
 'Spain',
 'Taiwan, Province of China',
 'Thailand',
 'Ukraine',
 'United Kingdom',
 'United States',
 'Vanuatu']

In [51]:
#1st cosine
#2nd index of the country similar

model_knn.kneighbors(features.loc['China'].values.reshape(1, -1), n_neighbors=3)

(array([[3.05311332e-14, 1.00000000e+00, 1.00000000e+00]]),
 array([[5, 1, 2]], dtype=int64))

In [57]:
#set up to check other countries

def country_choice(country):
    return model_knn.kneighbors(features.loc[country].values.reshape(1, -1), n_neighbors=3)

In [58]:
#call the country wish

country_choice('China')

(array([[3.05311332e-14, 1.00000000e+00, 1.00000000e+00]]),
 array([[5, 1, 2]], dtype=int64))